language: python
python:
  - 2.7

sudo: false

env:
  - TEST_DIR=tests/docs;
      GAE_PYTHONPATH=${HOME}/.cache/google_appengine;
      PATH=$PATH:${HOME}/google-cloud-sdk/bin;
      PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH};
      CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - TEST_DIR=tests/notebooks

before_install:
  # - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  # - conda update --yes conda
  - pip install --upgrade pip;
  - pip install -r requirements.txt

# command to install dependencies
install:
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PATH

# command to run tests
script:
  - nosetests $TEST_DIR


after_success:
  - cd docs
  - openssl aes-256-cbc -K $encrypted_c85711639858_key -iv $encrypted_c85711639858_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz ;
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine ;
  - export PATH=$PATH:${HOME}/google-cloud-sdk/bin ;
  - export PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} ;
  - python ../_ext/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
      curl https://sdk.cloud.google.com | bash;
    fi ;
  - gcloud auth activate-service-account --key-file credentials/client-secret.json ;
  - gcloud config set project simpegtutorials ;
  - gcloud -q components update gae-python ;
  - gcloud -q preview app deploy ./app.yaml --version ${TRAVIS_COMMIT} --promote;

notifications:
  email:
    - lindseyheagy@gmail.com
