language: python
python:
  - 2.7

sudo: false

env:
  - TEST_DIR=tests/docs;
      GAE_PYTHONPATH=${HOME}/.cache/google_appengine;
      PATH=$PATH:${HOME}/google-cloud-sdk/bin;
      PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH};
      CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - TEST_DIR=tests/notebooks

before_install:
  # - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  # - conda update --yes conda
  - pip install --upgrade pip;
  - pip install -r requirements.txt

# command to install dependencies
install:
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PATH

# command to run tests
script:
  - nosetests $TEST_DIR

after_success:
  - ./deploy.sh

notifications:
  email:
    - lindseyheagy@gmail.com
