language: python
python:
  - 2.7

sudo: false
cache:
  timeout: 3600
  pip: true
  directory:
  - ${HOME}/google_appengine
  - ${HOME}/google-cloud-sdk

env:
  - TEST_DIR=tests/docs;
      GAE_PYTHONPATH=${HOME}/.cache/google_appengine;
      PATH=$PATH:${HOME}/google-cloud-sdk/bin;
      PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH};
      CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - TEST_DIR=tests/notebooks

before_install:
  - cd ../../..
  - if [ ! -d "$GAE_PYTHONPATH" ]; then wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip;
    unzip -q google_appengine_1.9.38.zip; fi
  - if [ ! -d "$GCSDK_PATH" ]; then curl https://sdk.cloud.google.com | bash; fi
  - cd build/simpeg/tutorials

# command to install dependencies
install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PATH

# command to run tests
script:
  - nosetests $TEST_DIR

after_success:
  - deploy.sh

notifications:
  email:
    - lindseyheagy@gmail.com
