language: python
python:
  - 2.7

sudo: false
cache:
  timeout: 3600
  pip: true
  directory:
  - ${HOME}/google_appengine
  - ${HOME}/google-cloud-sdk

env:
  - TEST_DIR=tests/docs;
      GAE_PYTHONPATH=${HOME}/.cache/google_appengine;
      PATH=$PATH:${HOME}/google-cloud-sdk/bin;
      PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH};
      CLOUDSDK_CORE_DISABLE_PROMPTS=1; GAE_PROJECT=simpegtutorials
  - TEST_DIR=tests/notebooks

# command to install dependencies
install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PATH

# command to run tests
script:
  - nosetests $TEST_DIR

after_success:
  - if [ "$TEST_DIR" = "tests/docs" ]; then
      echo $PWD;
      ./deploy.sh;
    fi

notifications:
  email:
    - lindseyheagy@gmail.com
